# Neural Network

#### Model Training 
 * Numbber of layers
     * A neural network consists of:
        * Input Layer
        * Hidden Layers
        * Output Layer
 * Loss Function
   * Measures how far predictions are from actual values
   * Model tries to minimize loss
   * Ex:
     * Binary Classification -- binary_crossentropy
     * Multi-class Classification -- categorical_crossentropy
     * Regression -- mean_squared_error (MSE)
 * Activation
    * Introduce non-linearity into the model
 * Optimizer
   * Updates weights to reduce loss

## Keras Tuning 
### What is keras Tuning? 
* Keras Tuning Used to find the best hyperparameters for a model
* It Improves model performance automatically
* Model tries to : Find Optimal architecture, Reduce Validation loss,Increase accuracy

### What Can Be Tuned
* Number of layers
* Number of neurons
* Learning rate
* Batch size
* Dropout rate
* Activation functions

In [41]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [42]:
df = pd.read_csv(r"C:\Users\dadof\Downloads\diabetes.csv")
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [43]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [44]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [53]:
# Deep learning cannot acces DataFrames 
# So we converrt DataFrame into Numpy Arrays 

X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

In [54]:
X.shape, y.shape

((768, 8), (768,))

In [55]:
type(y)

numpy.ndarray

In [56]:
X.shape, y.shape

((768, 8), (768,))

In [57]:
from sklearn.model_selection import train_test_split

In [58]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.2,random_state=42)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((614, 8), (154, 8), (614,), (154,))

In [59]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
X_train_trans = sc.fit_transform(X_train)
X_test_trans = sc.transform(X_test)

type(X_train_trans), type(X_test_trans)

(numpy.ndarray, numpy.ndarray)

In [60]:
import keras

In [61]:
model = keras.Sequential([
    keras.Input(shape= (8, )),
    keras.layers.Dense(32, activation="relu", name= "H1"),
    keras.layers.Dense(1, activation="sigmoid")
])

In [62]:
model.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ H1 (Dense)                           │ (None, 32)                  │             288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [63]:
model.compile(loss = "binary_crossentropy", optimizer= "adam", metrics = ["accuracy"])

In [64]:
history = model.fit(
    X_train,
    y_train,
    epochs = 10,
    validation_data = (X_test, y_test),
    batch_size = 32
)

Epoch 1/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 28ms/step - accuracy: 0.5668 - loss: 10.8174 - val_accuracy: 0.4026 - val_loss: 8.4915
Epoch 2/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4267 - loss: 5.5667 - val_accuracy: 0.4221 - val_loss: 5.5401
Epoch 3/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.4691 - loss: 4.1891 - val_accuracy: 0.4610 - val_loss: 4.4024
Epoch 4/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.4951 - loss: 3.3860 - val_accuracy: 0.4740 - val_loss: 3.7000
Epoch 5/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.5179 - loss: 2.7129 - val_accuracy: 0.4870 - val_loss: 2.8108
Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5391 - loss: 2.1813 - val_accuracy: 0.5195 - val_loss: 2.3239
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5586 - loss: 1.7697 - val_accuracy: 0.5065 - val_loss: 1.8617
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.6042 - loss: 1.4471 - val_accuracy: 0.5779 - val_loss: 1.4609
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5977 - loss: 1.2555 - val_accuracy: 0.5649 - val_loss: 1.3010
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6124 - loss: 1.0893 - val_accuracy: 0.6104 - val_loss: 1.1996

In [65]:
!pip install -U keras-tuner

Defaulting to user installation because normal site-packages is not writeable
Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in c:\users\dadof\appdata\roaming\python\python312\site-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in c:\programdata\anaconda3\lib\site-packages (from keras-tuner) (24.1)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from keras-tuner) (2.32.3)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in c:\users\dadof\appdata\roaming\python\python312\site-packages (from keras-tuner) (1.78.1)
Requirement already satisfied: protobuf in c:\users\dadof\appdata\roaming\python\python312\site-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in c:\users\dadof\appdata\roaming\python\python312\site-packages (from grpcio->keras-tuner) (4.15.0)
Requirement already satisfied: absl-py in c:\users\dadof\appdata\roaming\python\python312\site-packages (from keras->keras-tuner) (2.4.0)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from keras->keras-tuner) (1.26.4)
Requirement already satisfied: rich in c:\users\dadof\appdata\roaming\python\python312\site-packages (from keras->keras-tuner) (14.3.3)
Requirement already satisfied: namex in c:\users\dadof\appdata\roaming\python\python312\site-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in c:\programdata\anaconda3\lib\site-packages (from keras->keras-tuner) (3.11.0)
Requirement already satisfied: optree in c:\users\dadof\appdata\roaming\python\python312\site-packages (from keras->keras-tuner) (0.18.0)
Requirement already satisfied: ml-dtypes in c:\users\dadof\appdata\roaming\python\python312\site-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\programdata\anaconda3\lib\site-packages (from requests->keras-tuner) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->keras-tuner) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dadof\appdata\roaming\python\python312\site-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dadof\appdata\roaming\python\python312\site-packages (from requests->keras-tuner) (2025.8.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\programdata\anaconda3\lib\site-packages (from rich->keras->keras-tuner) (2.15.1)
Requirement already satisfied: mdurl~=0.1 in c:\programdata\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.0)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [69]:
import keras_tuner as kt

In [70]:
dir(kt)

['BayesianOptimization',
 'GridSearch',
 'HyperModel',
 'HyperParameters',
 'Hyperband',
 'Objective',
 'Oracle',
 'RandomSearch',
 'SklearnTuner',
 'Tuner',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'applications',
 'engine',
 'errors',
 'oracles',
 'src',
 'synchronized',
 'tuners']

## Choosing Best Optimizer

In [71]:
def build_model(hp):
  model = keras.Sequential([
    keras.Input(shape= (8, )),
    keras.layers.Dense(32, activation="relu", name= "H1"),
    keras.layers.Dense(1, activation="sigmoid", name = "Output")])

  Loss = "binary_crossentropy"
  Optimizer = hp.Choice("optimizer", ["adam", "sgd", "rmsprop", "adadelta"])
  Metric = ["accuracy"]

  model.compile(loss = Loss, optimizer= Optimizer, metrics = Metric)

  return model

In [72]:
tuner = kt.RandomSearch(build_model,
                        objective = "val_accuracy",
                        max_trials=5)
tuner

In [73]:
tuner.search(X_train,
             y_train,
             epochs = 5,
             validation_data= (X_test, y_test))

Trial 4 Complete [00h 00m 03s]
val_accuracy: 0.6363636255264282

Best val_accuracy So Far: 0.6753246784210205
Total elapsed time: 00h 00m 19s

In [74]:
model = tuner.get_best_models()[0]
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ H1 (Dense)                           │ (None, 32)                  │             288 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ Output (Dense)                       │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [75]:
history = model.fit(
    X_train,
    y_train,
    epochs = 10,
    initial_epoch = 5,
    validation_data = (X_test, y_test),
    batch_size = 32
)

Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 25ms/step - accuracy: 0.6629 - loss: 0.6388 - val_accuracy: 0.6688 - val_loss: 0.6196
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6775 - loss: 0.6306 - val_accuracy: 0.5000 - val_loss: 0.7420
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6726 - loss: 0.6239 - val_accuracy: 0.5390 - val_loss: 0.7619
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6726 - loss: 0.6224 - val_accuracy: 0.6688 - val_loss: 0.6739
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6824 - loss: 0.6279 - val_accuracy: 0.6623 - val_loss: 0.6158

## Choosing Number of Layers/Neurons

In [76]:
def build_model(hp):

  Units = hp.Int("units", min_value = 8, max_value = 128, step = 8)
  model = keras.Sequential([
    keras.Input(shape= (8, )),
    keras.layers.Dense(units=Units, activation="relu", name= "H1"),
    keras.layers.Dense(1, activation="sigmoid", name = "Output")])

  Loss = "binary_crossentropy"
  # Optimizer = hp.Choice("optimizer", ["adam", "sgd", "rmsprop", "adadelta"])
  Optimizer = "sgd"
  Metric = ["accuracy"]

  model.compile(loss = Loss, optimizer= Optimizer, metrics = Metric)

  return model

In [77]:
tuner = kt.RandomSearch(build_model,
                        objective = "val_accuracy",
                        max_trials= 5,
                        directory = "mydir")

In [78]:
tuner.search(X_train,
             y_train,
             epochs = 5,
             validation_data = (X_test, y_test)
             )

Trial 5 Complete [00h 00m 03s]
val_accuracy: 0.6428571343421936

Best val_accuracy So Far: 0.7077922224998474
Total elapsed time: 00h 00m 18s

In [79]:
model = tuner.get_best_models()[0]
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ H1 (Dense)                           │ (None, 56)                  │             504 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ Output (Dense)                       │ (None, 1)                   │              57 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 561 (2.19 KB)

 Trainable params: 561 (2.19 KB)

 Non-trainable params: 0 (0.00 B)

In [80]:
history = model.fit(
    X_train,
    y_train,
    epochs = 10,
    initial_epoch = 5,
    validation_data = (X_test, y_test),
    batch_size = 32
)

Epoch 6/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step - accuracy: 0.6743 - loss: 0.6105 - val_accuracy: 0.6883 - val_loss: 0.6350
Epoch 7/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6889 - loss: 0.5954 - val_accuracy: 0.6818 - val_loss: 0.6161
Epoch 8/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6987 - loss: 0.6003 - val_accuracy: 0.6753 - val_loss: 0.6773
Epoch 9/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6889 - loss: 0.6128 - val_accuracy: 0.6623 - val_loss: 0.6505
Epoch 10/10
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6792 - loss: 0.6135 - val_accuracy: 0.7273 - val_loss: 0.6039